version: "3.5"

secrets:
  orthanc.secret.json:
    file: ./orthanc/config.json

services:
  orthanc-db:
    image: postgres
    container_name: orthanc-db
    environment:
      POSTGRES_PASSWORD: "pg-password"
    volumes:
      - ./orthanc/db:/var/lib/postgresql/data

  orthanc:
    image: orthancteam/orthanc
    container_name: orthanc
    ports:
      - 8042:8042
    environment:
      VERBOSE_ENABLED: "true"
      VERBOSE_STARTUP: "true"
      DICOM_WEB_PLUGIN_ENABLED: "true"
      OHIF_PLUGIN_ENABLED: "true"
      AUTHORIZATION_PLUGIN_ENABLED: "true"
      VOLVIEW_PLUGIN_ENABLED: "true"
    volumes:
      - ./orthanc/data:/var/lib/orthanc/db
    secrets:
      - orthanc.secret.json
    depends_on:
      - orthanc-db

  authenticator:
    container_name: authenticator
    build:
      context: ./authenticator
      dockerfile: Dockerfile
    command: npm run dev
    volumes:
      - ./authenticator:/usr/app/
      - /usr/app/node_modules
    ports:
      - "8200:8200"

  ohif:
    image: ohif/app:latest
    container_name: ohif
    volumes:
      - ./ohif/config.js:/usr/share/nginx/html/app-config.js
    ports:
      - "3000:80"
    depends_on:
      - orthanc

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "3080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - orthanc
      - ohif
